1. **Calcular a média da temperatura da amostra**

In [2]:
import pandas as pd

import numpy as np

df = pd.read_csv('RN-NATAL-2023.CSV', delimiter=';', skiprows=8, encoding='latin1')

In [4]:
df

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2023/01/01,0000 UTC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023/01/01,0100 UTC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023/01/01,0200 UTC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023/01/01,0300 UTC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023/01/01,0400 UTC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2023/12/31,1900 UTC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8756,2023/12/31,2000 UTC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8757,2023/12/31,2100 UTC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8758,2023/12/31,2200 UTC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8759,2023/12/31,2300 UTC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df_temperatura = df['TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)']
df_temperatura = pd.to_numeric(df_temperatura, errors='coerce')
df_temperatura = df_temperatura.replace(np.nan,0)

df_temperatura_media = round(df_temperatura.mean(),2)
df_temperatura_moda = round(df_temperatura.mode(),2)
df_temperatura_mediana = round(df_temperatura.median(),2)
df_temperatura_std = round(df_temperatura.std(),2)
df_temperatura_max = round(df_temperatura.max(),2)
df_temperatura_min = round(df_temperatura.min(),2)

print(f'média da temperatura ar - bulbo seco: {df_temperatura_media}')
print(f'moda da temperatura ar - bulbo seco: {df_temperatura_moda}')
print(f'mediana da temperatura ar - bulbo seco: {df_temperatura_mediana}')
print(f'desvio padrao da temperatura ar - bulbo seco: {df_temperatura_std}')
print(f'máx temperatura ar - bulbo seco: {df_temperatura_max}')
print(f'min temperatura ar - bulbo seco: {df_temperatura_min}')

média da temperatura ar - bulbo seco: 1.81
moda da temperatura ar - bulbo seco: 0    0.0
Name: TEMPERATURA DO AR - BULBO SECO, HORARIA (°C), dtype: float64
mediana da temperatura ar - bulbo seco: 0.0
desvio padrao da temperatura ar - bulbo seco: 6.76
máx temperatura ar - bulbo seco: 31.0
min temperatura ar - bulbo seco: 0.0

2. **Retirar nulos da coluna 'RADIACAO GLOBAL (Kj/m2)'**

In [6]:
df_radiacao = df['RADIACAO GLOBAL (Kj/m²)']

print(f'Qtd de nulos na coluna radiacao: {df_radiacao.isnull().sum()}') 

df_radiacao_sem_null = df_radiacao.dropna()

print(f'Qtd de nulos após remoção de nulos: {df_radiacao_sem_null.isnull().sum()}')

Qtd de nulos na coluna radiacao: 5303
Qtd de nulos após remoção de nulos: 0

3. **Copiar o dataframe reduzindo para 3 colunas (a sua escolha) e 1000 linhas (aleatórias)**

In [13]:
df_amostra_1000 = df[['TEMPERATURA DO PONTO DE ORVALHO (°C)','UMIDADE RELATIVA DO AR, HORARIA (%)','VENTO, RAJADA MAXIMA (m/s)']].sample(1000)
df_amostra_1000

,TEMPERATURA DO PONTO DE ORVALHO (°C),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, RAJADA MAXIMA (m/s)"
2829,"24,4",80.0,"5,8"
5578,23,80.0,8
3342,"23,7",93.0,"4,5"
1715,"23,6",71.0,"6,6"
1421,"23,1",79.0,"7,4"
...,...,...,...
202,NaN,NaN,NaN
5399,"21,5",84.0,"9,3"
925,"22,4",65.0,"9,5"
7067,NaN,NaN,NaN
5082,"20,2",62.0,"12,6"

In [14]:
df_amostra_1000.shape

(1000, 3)